#include "Physics.h"
#include <math.h>
namespace Physics {
static bool val(const String& d,const char* key,double& out){String low=d;low.toLowerCase();String k=String(key);k.toLowerCase();int p=low.indexOf(k+"=");if(p<0){p=low.indexOf(k+" ");if(p<0)return false;while(p<low.length()&&low[p]!='=')p++;if(p>=low.length())return false;}p=low.indexOf('=',p)+1;while(p<low.length()&&low[p]==' ')p++;int e=p;while(e<low.length()&&low[e]!=','&&low[e]!=';'&&low[e]!=' ')e++;String s=low.substring(p,e);out=s.toDouble();return s.length()>0;}
static String f(double x){if(!isfinite(x))return "indefinido";if(fabs(x-round(x))<1e-9)return String((long long)round(x));return String(x,6);}
const char* name(uint8_t t){switch(t){case 0:return "Forca";case 1:return "Velocidade";case 2:return "Distancia";case 3:return "Aceleracao";case 4:return "Tempo";case 5:return "Energia";case 6:return "Potencia";case 7:return "Densidade";case 8:return "Trabalho";case 9:return "Energia potencial";default:return "Fisica";}}
String formula(uint8_t t){switch(t){case 0:return "F = m · a";case 1:return "v = d / t";case 2:return "d = v · t";case 3:return "a = (vf - vi) / t";case 4:return "t = d / v";case 5:return "E = P · t";case 6:return "P = E / t";case 7:return "ρ = m / V";case 8:return "W = F · d";case 9:return "Ep = m · g · h";default:return "";}}
String solve(uint8_t t,const String&d){double m=0,a=0,F=0,v=0,di=0,tm=0,vi=0,vf=0,E=0,P=0,V=0,g=0,h=0;switch(t){case 0:if(val(d,"m",m)&&val(d,"a",a))return "F = m·a\nF = "+f(m)+"·"+f(a)+"\nF = "+f(m*a)+" N";break;case 1:if(val(d,"d",di)&&val(d,"t",tm)&&tm!=0)return "v = d/t\nv = "+f(di)+"/"+f(tm)+"\nv = "+f(di/tm)+" m/s";break;case 2:if(val(d,"v",v)&&val(d,"t",tm))return "d = v·t\nd = "+f(v)+"·"+f(tm)+"\nd = "+f(v*tm)+" m";break;case 3:if(val(d,"vf",vf)&&val(d,"vi",vi)&&val(d,"t",tm)&&tm!=0)return "a = (vf-vi)/t\na = ("+f(vf)+"-"+f(vi)+")/"+f(tm)+"\na = "+f((vf-vi)/tm)+" m/s²";break;case 4:if(val(d,"d",di)&&val(d,"v",v)&&v!=0)return "t = d/v\nt = "+f(di)+"/"+f(v)+"\nt = "+f(di/v)+" s";break;case 5:if(val(d,"P",P)&&val(d,"t",tm))return "E = P·t\nE = "+f(P)+"·"+f(tm)+"\nE = "+f(P*tm)+" J";break;case 6:if(val(d,"E",E)&&val(d,"t",tm)&&tm!=0)return "P = E/t\nP = "+f(E)+"/"+f(tm)+"\nP = "+f(E/tm)+" W";break;case 7:if(val(d,"m",m)&&val(d,"V",V)&&V!=0)return "ρ = m/V\nρ = "+f(m)+"/"+f(V)+"\nρ = "+f(m/V)+" kg/m³";break;case 8:if(val(d,"F",F)&&val(d,"d",di))return "W = F·d\nW = "+f(F)+"·"+f(di)+"\nW = "+f(F*di)+" J";break;case 9:if(val(d,"m",m)&&val(d,"g",g)&&val(d,"h",h))return "Ep = m·g·h\nEp = "+f(m)+"·"+f(g)+"·"+f(h)+"\nEp = "+f(m*g*h)+" J";break;}return "Ainda faltam dados.\nEx.: m=2,a=3";}
String autoSolve(const String&d){double v=0; if(val(d,"m",v)){} return "Escolha o que deseja calcular para o assistente encontrar a formula.";}
}
